file.choose
myfile <- file.choose()
mms.data <- read.csv(myfile,header=TRUE)
head(mms.data)
summary(mms.data)
install.packages("descr")
library(descr)
descr(mms.data)
mms.data.bags <- mms.data[which(mms.data$id==1),] 
head(mms.data.bags)
summary(mms.data.bags)
fivenum(mms.data.bags$weight)
hist(mms.data.bags)
x <- rbeta(mms.data.bags)
x <- rbeta(64,5,2)
summary(x)
sd(x)
var(x)
hist(x)
lines
density(x)
par(mfrow=c(1,2))
hist(x, col="gray", xlab="Sampled Values", ylab="Frequency of Occurence", main="Frequency")
par(mfrow=c(2,1))
hist(mms.data.bags$weight)
hist(mms.data.bags$weight, xlab="M&Ms Weight Distribution")
hist(mms.data.bags$weight, main="M&Ms Weight Histogram")
hist(mms.data.bags$weight, xlab="M&Ms Weight Distribution",main="M&Ms Weight Histogram")
boxplot(mms.data.bags$weight, main="Box Plot of M&Ms Weight",ylim=c(42,52), xlab="M&Ms Weight (g)",horizontal=TRUE)
plot(mms.data$weight, mms.data$total.number, main="M&Ms Weight vs. Total Number", xlab="Weight (g)",ylab="Total number (#'s)")
